owner: facu8990 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Sudestec Cloud
    url: https://own.sudestec.ar/login
  - name: Sudestec App
    url: https://app.sudestec.ar
  - name: Sudestec API
    url: https://api.sudestec.ar/_/#/login

status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Sudestec Status**"
  introMessage: Status page for Sudestec products.
  navbar:
    - title: Sudestec Cloud
      href: https://own.sudestec.ar
    - title: Sudestec App
      href: https://app.sudestec.ar
    - title: Sudestec API
      href: https://api.sudestec.ar/_/
